### ISSUE TITLE
想解密几个p文件，能有联系方式吗？

### ISSUE THREAD

**Issue by zhao19851019** [datahackor/MATLAB-P-CODE-Decrypt#2]

**Comment by datahackor** [comment]
发到这个邮箱就可以啊，不过要看我有没有时间。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月25日(周日) 晚上11:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [datahackor/MATLAB-P-CODE-Decrypt] 想解密几个p文件，能有联系方式吗？ (#2)

**Comment by zhao19851019** [comment]
麻烦您有时间解密一下这几个文件。不胜感激！！！
&nbsp;

**Comment by datahackor** [comment]
文件在哪呢？

**Comment by zhao19851019** [comment]
您得到吗？需要解密的第一次我发在附件里了。



发自我的iPhone

**Comment by datahackor** [comment]
email: 529767489@qq.com
