### ISSUE TITLE
我有几个p文件想解密，可否留个联系方式？

### ISSUE THREAD

**Issue by yumxcode** [datahackor/MATLAB-P-CODE-Decrypt#3]

**Comment by hsqaihkl** [comment]
可以有偿帮忙破解，需要的email我898425209@qq.com

**Comment by hsqaihkl** [comment]
qq:898425209
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月23日 20:44 |
| 收件人 | datahackor/MATLAB-P-CODE-Decrypt ***@***.***> |
| 抄送人 | Water ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [datahackor/MATLAB-P-CODE-Decrypt] 我有几个p文件想解密，可否留个联系方式？ (Issue #3) |

Closed #3 as completed.
